# Generated by Django 4.2.5 on 2023-10-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("creador", models.CharField(max_length=50)),
                ("sinopsis", models.TextField()),
                ("temporadas", models.IntegerField()),
                ("fecha_estreno", models.DateField()),
            ],
        ),
    ]
