# Generated by Django 4.2.5 on 2023-10-14 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("serie", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serie",
            name="sinopsis",
        ),
    ]
