# Generated by Django 4.2.5 on 2023-10-14 17:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("serie", "0002_remove_serie_sinopsis"),
    ]

    operations = [
        migrations.AddField(
            model_name="serie",
            name="sinopsis",
            field=ckeditor.fields.RichTextField(default=" "),
        ),
    ]
