# Generated by Django 4.2.5 on 2023-10-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pelicula",
            name="sinopsis",
            field=models.TextField(default=" "),
        ),
    ]
