# Generated by Django 4.2.5 on 2023-10-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0003_alter_pelicula_sinopsis"),
    ]

    operations = [
        migrations.AddField(
            model_name="pelicula",
            name="portada",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
